### ISSUE TITLE
Don't execute action when the package doesn't exist 

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/badge#31]
Ending up in error like:

```
2016-02-21 14:32:49+0400 [HTTPChannel,3,127.0.0.1] Unhandled Error
        Traceback (most recent call last):
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/twisted/web/server.py", line 234, in render
            body = resrc.render(self)
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/klein/resource.py", line 201, in render
            d = defer.maybeDeferred(_execute)
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/klein/resource.py", line 195, in _execute
            **kwargs)
        --- <exception caught here> ---
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/klein/app.py", line 108, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/klein/app.py", line 193, in _f
            return _call(instance, f, request, *a, **kw)
          File "/home/alireza/.virtualenvs/badge/lib/python2.7/site-packages/klein/app.py", line 33, in _call
            return f(*args, **kwargs)
          File "/home/alireza/dev/pycharm/badge/badge/views.py", line 50, in service_badge
            getattr(service_class, service_reg['actions'][action])()
          File "/home/alireza/dev/pycharm/badge/service/pypi/__init__.py", line 186, in action_license
            lie_sense = self.get_license()
          File "/home/alireza/dev/pycharm/badge/service/pypi/__init__.py", line 80, in get_license
            if (self.package_data.license
        exceptions.AttributeError: 'NoneType' object has no attribute 'license'

```

**Comment by Alir3z4** [comment]
```
    if service_class.package_pulling_failed:
        request.setResponseCode(404)
        return "Couldn't pull data from {} for package {}".format(service, package)

```
